OGR layers: fix memory leak with DWithin filter
Fixes leak introduced recently in master per 736baa6d55634efa027baffb08401ce38ef92caa

Fixes following failures with the Travis ASAN job:
FAILED run_test.py::test[wfs_filter_ogr_wfs_filter_dwithin_xml] - AssertionEr...
FAILED run_test.py::test[wfs_filter_ogr_wfs_filter_dwithin_units_xml] - Asser...
FAILED run_test.py::test[wfs_ogr_native_sql_wfs_ogr_native_sql_32_xml] - Asse...